### ISSUE TITLE
base_control操作說明問題

### ISSUE THREAD

**Issue by arenas7307979** [LFZ1994/base_control#1]
您好 請問安裝base_control以後, 跑launch檔
系統請我安裝move_base但操作手冊上好像不需要安裝？

**Comment by LFZ1994** [comment]
文档中有注明可能会出现这类错误，这是因为你使用自己搭建的环境，部分依赖的功能包并没有安装，需要根据提示手动安装





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"arenas7307979"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 中午11:13
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LFZ1994/base_control] base_control操作說明問題 (#1)





 
您好 請問安裝base_control以後, 跑launch檔
 系統請我安裝move_base但操作手冊上好像不需要安裝？

**Comment by arenas7307979** [comment]
請問有搖桿控制的範例嗎？ 或是可以參考的包

**Comment by LFZ1994** [comment]
遥控手柄和底盘是直接连接的，不依赖任何功能包，将手柄接收机连接到底盘上后按照下图操作即可（如果手柄和底盘是一同购买并收货的，接收机会内置在底盘中，不需要再额外接入），依照下图操作即可控制







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"arenas7307979"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 中午11:34
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"刘伏志"<lfz1994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LFZ1994/base_control] base_control操作說明問題 (#1)





 
請問有搖桿控制的範例嗎？ 或是可以參考的包

**Comment by arenas7307979** [comment]
好的, 最後請問開機的蜂鳴器可以調聲音大小 或是 不要靜音嗎？

**Comment by LFZ1994** [comment]
软件上没有调节的接口，如有需要可以拆开底盘将蜂鸣器用胶带贴住或者拆除






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"arenas7307979"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上6:20
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"刘伏志"<lfz1994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LFZ1994/base_control] base_control操作說明問題 (#1)





 
好的, 最後請問開機的蜂鳴器可以調聲音大小 或是 不要靜音嗎？

**Comment by cuizhongren45** [comment]
你好，我在跑base_control的时候，运行的时候会有一个“base_type”不存在的错误，我是自己做的地盘，上位机只有发送数据，不返回数据
