### ISSUE TITLE
無法使用base_control

### ISSUE THREAD

**Issue by petre841020** [LFZ1994/base_control#2]
因為裝其他東西導致更新了一些軟體
結果現在一直報錯Can not open Serial/dev/move_base
AttributrError: BaseControl instance has no attribute 'serial'

**Comment by LFZ1994** [comment]
新安装软件并不会导致这个问题，可能原因有三个：
误操作将系统内为底盘编写的udev规则删除
底盘USB接口未连接
其他软件占用了底盘所使用的端口




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"petre841020"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午3:02
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LFZ1994/base_control] 無法使用base_control (#2)





 
因為再裝其他東西導致更新了一些軟體
 結果現在一直報錯Can not open Serial/dev/move_base
 AttributrError: BaseControl instance has no attribute 'serial'

**Comment by petre841020** [comment]
下面是報錯的資訊
不好意思對這塊真的不是很熟悉我不清楚是那個問題
[INFO] [1593761353.296465]: NanoCar base control ...
[ERROR] [1593761353.344093]: Can not open Serial/dev/move_base
Traceback (most recent call last):
  File "/home/nanorobot/catkin_ws/src/base_control/script/base_control.py", line 582, in <module>
    bc = BaseControl()
  File "/home/nanorobot/catkin_ws/src/base_control/script/base_control.py", line 145, in __init__
    self.serial.close
AttributeError: BaseControl instance has no attribute 'serial'
[base_control-3] process has died [pid 3893, exit code 1, cmd /home/nanorobot/catkin_ws/src/base_control/script/base_control.py input_rgb_image:=/image_raw __name:=base_control __log:=/home/nanorobot/.ros/log/dccabeba-bcfe-11ea-9a7e-b827ebcb1f0c/base_control-3.log].
log file: /home/nanorobot/.ros/log/dccabeba-bcfe-11ea-9a7e-b827ebcb1f0c/base_control-3*.log

**Comment by LFZ1994** [comment]
你是使用我们提供的系统镜像吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"petre841020"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午3:34
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"刘伏志"<lfz1994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LFZ1994/base_control] 無法使用base_control (#2)





 
下面是報錯的資訊
 不好意思對這塊真的不是很熟悉我不清楚是那個問題
 [INFO] [1593761353.296465]: NanoCar base control ...
 [ERROR] [1593761353.344093]: Can not open Serial/dev/move_base
 Traceback (most recent call last):
 File "/home/nanorobot/catkin_ws/src/base_control/script/base_control.py", line 582, in 
 bc = BaseControl()
 File "/home/nanorobot/catkin_ws/src/base_control/script/base_control.py", line 145, in init
 self.serial.close
 AttributeError: BaseControl instance has no attribute 'serial'
 [base_control-3] process has died [pid 3893, exit code 1, cmd /home/nanorobot/catkin_ws/src/base_control/script/base_control.py input_rgb_image:=/image_raw __name:=base_control __log:=/home/nanorobot/.ros/log/dccabeba-bcfe-11ea-9a7e-b827ebcb1f0c/base_control-3.log].
 log file: /home/nanorobot/.ros/log/dccabeba-bcfe-11ea-9a7e-b827ebcb1f0c/base_control-3*.log

**Comment by petre841020** [comment]
我是購買ackerman系統車子nanorobot 裡面內建有base_control等其他系統
但昨天安裝一些東西之後就無法使用了
除了robot_camera.launch之外都不能使用

**Comment by LFZ1994** [comment]
你PC装下一teamviewer，我安排工程师远程看一下吧






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"petre841020"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午3:39
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"刘伏志"<lfz1994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LFZ1994/base_control] 無法使用base_control (#2)





 
我是購買ackerman系統車子nanorobot 裡面內建有base_control等其他系統
 但昨天安裝一些東西之後就無法使用了
 除了robot_camera.launch之外都不能使用

**Comment by petre841020** [comment]
你說的是SSH連接的電腦嗎

**Comment by LFZ1994** [comment]
是




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"petre841020"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午3:43
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"刘伏志"<lfz1994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LFZ1994/base_control] 無法使用base_control (#2)





 
你說的是SSH連接的電腦嗎

**Comment by petre841020** [comment]
id:1 734 332 969
密碼c6h5x7

**Comment by LFZ1994** [comment]
没有找到问题，看起来端口存在但就是无法打开，只能重新刷我们提供的系统镜像恢复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"petre841020"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午3:46
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"刘伏志"<lfz1994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LFZ1994/base_control] 無法使用base_control (#2)





 
id:1 734 332 969
 密碼c6h5x7

**Comment by petre841020** [comment]
你說重新下載這邊的base_control嗎

**Comment by LFZ1994** [comment]
不是，重新给树莓派安装我们提供的系统镜像！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"petre841020"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 下午4:05
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"刘伏志"<lfz1994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LFZ1994/base_control] 無法使用base_control (#2)





 
你說重新下載這邊的base_control嗎

**Comment by petre841020** [comment]
好的我試試謝謝

**Comment by petre841020** [comment]
我輸入sudo chmod 666 /dev/ttyAMA0
就可以使用了
但每次使用幾秒就自動關閉了
B聲一下後差不多兩秒就響兩聲B自動關閉了

**Comment by LFZ1994** [comment]
尝试重新烧录我们提供的系统镜像




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"petre841020"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月5日(星期天) 晚上8:44
收件人:&nbsp;"LFZ1994/base_control"<base_control@noreply.github.com&gt;;
抄送:&nbsp;"刘伏志"<lfz1994@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LFZ1994/base_control] 無法使用base_control (#2)





 
我輸入sudo chmod 666 /dev/ttyAMA0
 就可以使用了
 但每次使用幾秒就自動關閉了
 B聲一下後差不多兩秒就響兩聲B自動關閉了
